// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDezuj7apPKm7T-qUI7KDiNf84qgqv9tKM',
    appId: '1:653370201249:web:e4e9b0919da91b63b88ce0',
    messagingSenderId: '653370201249',
    projectId: 'mybook-f7793',
    authDomain: 'mybook-f7793.firebaseapp.com',
    databaseURL: 'https://mybook-f7793-default-rtdb.firebaseio.com',
    storageBucket: 'mybook-f7793.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0cLYcUp7GqaC8IogzOn4PPa8BXhiuCUI',
    appId: '1:653370201249:android:2506a68ce3c68322b88ce0',
    messagingSenderId: '653370201249',
    projectId: 'mybook-f7793',
    databaseURL: 'https://mybook-f7793-default-rtdb.firebaseio.com',
    storageBucket: 'mybook-f7793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRxDXKqsU3qL15LgNtoMKBuShOCih-lc',
    appId: '1:653370201249:ios:e2144238990eb88ab88ce0',
    messagingSenderId: '653370201249',
    projectId: 'mybook-f7793',
    databaseURL: 'https://mybook-f7793-default-rtdb.firebaseio.com',
    storageBucket: 'mybook-f7793.appspot.com',
    iosClientId: '653370201249-adq4jcgtgkvto4p4qf892bkrrbphkapv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitaby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRxDXKqsU3qL15LgNtoMKBuShOCih-lc',
    appId: '1:653370201249:ios:e2144238990eb88ab88ce0',
    messagingSenderId: '653370201249',
    projectId: 'mybook-f7793',
    databaseURL: 'https://mybook-f7793-default-rtdb.firebaseio.com',
    storageBucket: 'mybook-f7793.appspot.com',
    iosClientId: '653370201249-adq4jcgtgkvto4p4qf892bkrrbphkapv.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitaby',
  );
}
